name: Deploy to Test Lambda

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t .

    - name: Create deployment package
      run: zip -r code-compass-ask-question-lambda.zip .

    - name: Push Zip to S3
      uses: jakejarvis/s3-sync-action@v0.3.1
      with:
        args: --exclude '*' --include 'code-compass-ask-question-lambda.zip'
      env:
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: 'code-compass-lambdas'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy to lambda
      run: aws lambda update-function-code --function-name code-compass-ask-question-lambda --region us-east-1 --s3-bucket code-compass-lambdas --s3-key code-compass-ask-question-lambda.zip